# syland-theme-apply: the backend home/quickshell/src/theme/ColorLoader.qml
# already expects (it runs `syland-theme-apply quickshell` on startup and
# watches the file this writes) but that never actually existed until now.
#
# Themes live read-only under ~/.config/syland/themes-src/<name>/ (deployed
# by home/dotfiles.nix from home/themes/), each a <name>.<ext> default
# image + colors.toml (6 hand-authored keys: background, foreground,
# accent, red, green, yellow) + any other images as alternate backgrounds.
#
# Generated/writable state lives under ~/.config/syland/themes/ instead —
# quickshell.generated (ColorLoader's FileView target), ghostty.generated
# (included via ghostty's own config-file directive), hyprland.generated.lua
# (dofile'd from home/hypr/base.lua), colors.toml (symlink to the active
# theme's own file), state.json (what's currently applied).
{ pkgs, lib, ... }:
let
  themeApply = pkgs.writeShellApplication {
    name = "syland-theme-apply";
    runtimeInputs = [
      pkgs.yq
      pkgs.jq
      pkgs.awww
      pkgs.hyprland
      pkgs.coreutils
      pkgs.findutils
      pkgs.systemd
    ];
    text = ''
      THEMES_SRC="$HOME/.config/syland/themes-src"
      STATE_DIR="$HOME/.config/syland/themes"
      mkdir -p "$STATE_DIR"

      default_image() {
        local name="$1"
        for ext in png jpg jpeg webp; do
          local f="$THEMES_SRC/$name/$name.$ext"
          if [ -f "$f" ]; then
            echo "$f"
            return 0
          fi
        done
        return 1
      }

      # Prints "N:filename" for every <name>-N.<ext> file in a theme
      # (N a plain integer), sorted numerically by N. These are
      # toggle-only variation pictures -- hidden from list-images,
      # only reachable via the toggle subcommand -- distinguished
      # from ordinary alternate backgrounds purely by this numeric
      # suffix convention.
      list_variations() {
        local name="$1" f base
        for f in "$THEMES_SRC/$name"/*; do
          [ -f "$f" ] || continue
          base=$(basename "$f")
          if [[ "$base" =~ ^''${name}-([0-9]+)\.(png|jpg|jpeg|webp)$ ]]; then
            printf '%s:%s\n' "''${BASH_REMATCH[1]}" "$base"
          fi
        done | sort -t: -k1,1n
      }

      # mix_hex "#rrggbb" "#rrggbb" <ratio 0-100 toward the 2nd color>
      mix_hex() {
        local c1="''${1#\#}" c2="''${2#\#}" ratio="$3"
        local r1=$((16#''${c1:0:2})) g1=$((16#''${c1:2:2})) b1=$((16#''${c1:4:2}))
        local r2=$((16#''${c2:0:2})) g2=$((16#''${c2:2:2})) b2=$((16#''${c2:4:2}))
        printf '#%02x%02x%02x' \
          $(( (r1*(100-ratio)+r2*ratio)/100 )) \
          $(( (g1*(100-ratio)+g2*ratio)/100 )) \
          $(( (b1*(100-ratio)+b2*ratio)/100 ))
      }

      render_quickshell() {
        local bg="$1" fg="$2" accent="$3" red="$4" green="$5" yellow="$6"
        local tmp; tmp=$(mktemp)
        {
          printf '# managed by syland -- do not edit by hand, regenerated by syland-theme-apply\n'
          jq -nc --arg background "$bg" --arg foreground "$fg" --arg accent "$accent" \
            --arg red "$red" --arg green "$green" --arg yellow "$yellow" \
            '{background:$background,foreground:$foreground,accent:$accent,red:$red,green:$green,yellow:$yellow}'
        } > "$tmp"
        mv "$tmp" "$STATE_DIR/quickshell.generated"
      }

      # Ghostty needs a 16-slot ANSI palette but colors.toml only
      # authors 6 semantic colors, so slots 0-7 map directly and the
      # rest (magenta/cyan + all 8 "bright" variants) are derived via
      # mix_hex -- an approximation, not something to hand-tune per
      # theme.
      render_ghostty() {
        local bg="$1" fg="$2" accent="$3" red="$4" green="$5" yellow="$6"
        local magenta cyan bright_black bright_white
        magenta=$(mix_hex "$red" "$accent" 50)
        cyan=$(mix_hex "$green" "$accent" 50)
        bright_black=$(mix_hex "$bg" "#ffffff" 25)
        bright_white=$(mix_hex "$fg" "#ffffff" 10)
        local tmp; tmp=$(mktemp)
        {
          printf '# managed by syland -- do not edit by hand, regenerated by syland-theme-apply\n'
          printf 'background = %s\nforeground = %s\n' "$bg" "$fg"
          printf 'palette = 0=%s\n' "$bg"
          printf 'palette = 1=%s\n' "$red"
          printf 'palette = 2=%s\n' "$green"
          printf 'palette = 3=%s\n' "$yellow"
          printf 'palette = 4=%s\n' "$accent"
          printf 'palette = 5=%s\n' "$magenta"
          printf 'palette = 6=%s\n' "$cyan"
          printf 'palette = 7=%s\n' "$fg"
          printf 'palette = 8=%s\n' "$bright_black"
          printf 'palette = 9=%s\n' "$(mix_hex "$red" "#ffffff" 20)"
          printf 'palette = 10=%s\n' "$(mix_hex "$green" "#ffffff" 20)"
          printf 'palette = 11=%s\n' "$(mix_hex "$yellow" "#ffffff" 20)"
          printf 'palette = 12=%s\n' "$(mix_hex "$accent" "#ffffff" 20)"
          printf 'palette = 13=%s\n' "$(mix_hex "$magenta" "#ffffff" 20)"
          printf 'palette = 14=%s\n' "$(mix_hex "$cyan" "#ffffff" 20)"
          printf 'palette = 15=%s\n' "$bright_white"
        } > "$tmp"
        mv "$tmp" "$STATE_DIR/ghostty.generated"

        # Ghostty is single-instance (GTK/D-Bus activation): every
        # `ghostty` invocation -- including Hyprland's own terminal
        # keybind -- proxies to the one already-running process,
        # which only reads config files at its own original
        # startup. New windows do NOT get a fresh read on their
        # own (confirmed live: a window opened after a theme
        # switch still showed the old colors). Its org.gtk.Actions
        # D-Bus interface exposes reload-config as a real,
        # externally-triggerable action (confirmed via `busctl
        # --user call com.mitchellh.ghostty
        # /com/mitchellh/ghostty org.gtk.Actions List`), so call
        # it here instead of relying on the in-app keybind.
        # `|| true` because ghostty may not be running at all
        # (nothing to reload) and that's not a theme-switch
        # failure.
        busctl --user call com.mitchellh.ghostty /com/mitchellh/ghostty \
          org.gtk.Actions Activate "sava{sv}" reload-config 0 0 >/dev/null 2>&1 || true
      }

      # Active border = accent; inactive = background blended 30%
      # toward foreground, so it reads as "dim" rather than invisible.
      render_hyprland() {
        local bg="$1" fg="$2" accent="$3"
        local inactive; inactive=$(mix_hex "$bg" "$fg" 30)
        local tmp; tmp=$(mktemp)
        printf -- '-- managed by syland -- do not edit by hand, regenerated by syland-theme-apply\nreturn { ["col.active_border"] = "rgba(%sff)", ["col.inactive_border"] = "rgba(%sff)" }\n' \
          "''${accent#\#}" "''${inactive#\#}" > "$tmp"
        mv "$tmp" "$STATE_DIR/hyprland.generated.lua"
      }

      render_nvim() {
        local bg="$1" fg="$2" accent="$3" red="$4" green="$5" yellow="$6"
        local comment cursorline visual pmenu pmenu_sel diff_add diff_delete diff_change
        comment=$(mix_hex "$bg" "$fg" 50)
        cursorline=$(mix_hex "$bg" "$fg" 10)
        visual=$(mix_hex "$bg" "$accent" 25)
        pmenu=$(mix_hex "$bg" "$fg" 8)
        pmenu_sel=$(mix_hex "$bg" "$accent" 30)
        diff_add=$(mix_hex "$bg" "$green" 20)
        diff_delete=$(mix_hex "$bg" "$red" 20)
        diff_change=$(mix_hex "$bg" "$yellow" 20)

        local tmp; tmp=$(mktemp)
        {
                      printf -- '-- managed by syland -- do not edit by hand, regenerated by syland-theme-apply\n'
              printf 'return {\n'
              printf '  background = "%s",\n' "$bg"
              printf '  foreground = "%s",\n' "$fg"
              printf '  accent = "%s",\n' "$accent"
              printf '  red = "%s",\n' "$red"
              printf '  green = "%s",\n' "$green"
              printf '  yellow = "%s",\n' "$yellow"
              printf '  comment = "%s",\n' "$comment"
              printf '  cursorline = "%s",\n' "$cursorline"
              printf '  visual = "%s",\n' "$visual"
              printf '  pmenu = "%s",\n' "$pmenu"
              printf '  pmenu_sel = "%s",\n' "$pmenu_sel"
              printf '  diff_add = "%s",\n' "$diff_add"
              printf '  diff_delete = "%s",\n' "$diff_delete"
              printf '  diff_change = "%s",\n' "$diff_change"
              printf '}\n'
        } > "$tmp"
        mv "$tmp" "$STATE_DIR/nvim.generated.lua"
      }

      render_all() {
        local theme="$1"
        local toml="$THEMES_SRC/$theme/colors.toml"
        local json; json=$(tomlq -c . "$toml")
        local bg fg accent red green yellow
        bg=$(jq -r .background <<<"$json")
        fg=$(jq -r .foreground <<<"$json")
        accent=$(jq -r .accent <<<"$json")
        red=$(jq -r .red <<<"$json")
        green=$(jq -r .green <<<"$json")
        yellow=$(jq -r .yellow <<<"$json")

        render_quickshell "$bg" "$fg" "$accent" "$red" "$green" "$yellow"
        render_ghostty "$bg" "$fg" "$accent" "$red" "$green" "$yellow"
        render_hyprland "$bg" "$fg" "$accent"
        render_nvim "$bg" "$fg" "$accent" "$red" "$green" "$yellow"

        ln -sf "$toml" "$STATE_DIR/colors.toml"
        hyprctl reload config-only
      }

      # do_apply <theme> [image] -- shared by the `apply` and
      # `toggle` subcommands so there's exactly one place that
      # renders colors, sets the wallpaper, and persists state.
      do_apply() {
        local theme="$1" image="''${2:-}" img_path img_name tmp
        render_all "$theme"
        if [ -n "$image" ]; then
          img_path="$THEMES_SRC/$theme/$image"
        else
          img_path=$(default_image "$theme")
        fi
        awww img "$img_path" --resize crop -t wipe
        img_name=$(basename "$img_path")
        tmp=$(mktemp)
        jq -nc --arg theme "$theme" --arg image "$img_name" '{theme:$theme, image:$image}' > "$tmp"
        mv "$tmp" "$STATE_DIR/state.json"
      }

      cmd="''${1:-}"
      case "$cmd" in
        quickshell)
          if [ ! -e "$STATE_DIR/colors.toml" ]; then
            echo "syland-theme-apply: no active theme yet, skipping" >&2
            exit 0
          fi
          json=$(tomlq -c . "$STATE_DIR/colors.toml")
          render_quickshell \
            "$(jq -r .background <<<"$json")" "$(jq -r .foreground <<<"$json")" \
            "$(jq -r .accent <<<"$json")" "$(jq -r .red <<<"$json")" \
            "$(jq -r .green <<<"$json")" "$(jq -r .yellow <<<"$json")"
          ;;
        list-themes)
          print_theme() {
            local name="$1" img has_variation
            img=$(default_image "$name") || return 0
            has_variation=false
            [ -n "$(list_variations "$name")" ] && has_variation=true
            jq -nc --arg name "$name" --arg default_image "$img" --argjson has_variation "$has_variation" \
              '{name:$name, default_image:$default_image, has_variation:$has_variation}'
          }
          # syland is the default theme, always listed first
          # regardless of directory order.
          if [ -d "$THEMES_SRC/syland" ]; then
            print_theme "syland"
          fi
          for d in "$THEMES_SRC"/*/; do
            [ -d "$d" ] || continue
            name=$(basename "$d")
            [ "$name" = "syland" ] && continue
            print_theme "$name"
          done
          ;;
        list-images)
          theme="''${2:?usage: syland-theme-apply list-images <theme>}"
          # The default background is a real selectable option
          # too (to switch back to it after picking something
          # else), listed first so it's easy to find.
          def=$(default_image "$theme" || true)
          if [ -n "$def" ]; then
            jq -nc --arg name "$(basename "$def")" --arg path "$def" '{name:$name, path:$path}'
          fi
          # Variation pictures (<name>-N.<ext>) are toggle-only --
          # excluded here the same way the default image already is.
          variation_names=$(list_variations "$theme" | cut -d: -f2-)
          find -L "$THEMES_SRC/$theme" -maxdepth 1 -type f \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.webp' \) \
            | while read -r f; do
              [ "$f" = "$def" ] && continue
              grep -Fxq "$(basename "$f")" <<<"$variation_names" && continue
              jq -nc --arg name "$(basename "$f")" --arg path "$f" '{name:$name, path:$path}'
            done
          ;;
        current)
          if [ -f "$STATE_DIR/state.json" ]; then
            cat "$STATE_DIR/state.json"
          else
            echo '{}'
          fi
          ;;
        apply)
          do_apply "''${2:?usage: syland-theme-apply apply <theme> [image]}" "''${3:-}"
          ;;
        toggle)
          # Cycles the *current* theme's picture through its
          # hidden <name>-N.<ext> variations and back to the
          # default -- colors never change, only the wallpaper.
          # No-ops (exits quietly) if there's no active theme
          # yet, or that theme has no variation pictures.
          [ -f "$STATE_DIR/state.json" ] || exit 0
          theme=$(jq -r .theme "$STATE_DIR/state.json")
          image=$(jq -r .image "$STATE_DIR/state.json")

          mapfile -t variations < <(list_variations "$theme")
          [ "''${#variations[@]}" -eq 0 ] && exit 0

          found=false
          next_name=""
          for i in "''${!variations[@]}"; do
            name="''${variations[$i]#*:}"
            if [ "$name" = "$image" ]; then
              found=true
              next_index=$((i + 1))
              if [ "$next_index" -lt "''${#variations[@]}" ]; then
                next_name="''${variations[$next_index]#*:}"
              fi
              break
            fi
          done
          if ! $found; then
            # Currently on the default (or some other ordinary
            # picture) -- go to the first variation.
            next_name="''${variations[0]#*:}"
          elif [ -z "$next_name" ]; then
            # Was the last variation -- wrap back to default.
            next_name=$(basename "$(default_image "$theme")")
          fi

          do_apply "$theme" "$next_name"
          ;;
        *)
          echo "usage: syland-theme-apply {quickshell|list-themes|list-images <theme>|current|apply <theme> [image]|toggle}" >&2
          exit 1
          ;;
      esac
    '';
  };

  # Same Mocha values as home/themes/mocha/colors.toml, in each target's
  # own generated format -- what's on screen before the panel is ever
  # opened, and identical to what applying that theme for real produces.
in
{
  home.packages = [ themeApply ];

  # Idempotent first-run safety net: guarantees the 3 generated files
  # ColorLoader/ghostty/hyprland all expect to be able to read exist even
  # before the panel is ever opened. Never overwrites once a real theme
  # has actually been applied.
  #
  # Written fully flush-left deliberately: Nix's indented-string dedent
  # only fires when every content line AND the closing '' share the same
  # leading whitespace, and the closing '' line's own indentation becomes
  # literal trailing content otherwise (confirmed by testing this exact
  # pattern) -- easiest to just never indent anything inside a heredoc.
  home.activation.sylandThemeSeed = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    STATE_DIR="$HOME/.config/syland/themes"
    mkdir -p "$STATE_DIR"
    [ -e "$STATE_DIR/quickshell.generated" ] || cat > "$STATE_DIR/quickshell.generated" <<'EOF'
    # managed by syland -- seeded by home-manager activation, overwritten by syland-theme-apply
    {"background":"#1e1e2e","foreground":"#cdd6f4","accent":"#89b4fa","red":"#f38ba8","green":"#a6e3a1","yellow":"#f9e2af"}
    EOF
    [ -e "$STATE_DIR/ghostty.generated" ] || cat > "$STATE_DIR/ghostty.generated" <<'EOF'
    # managed by syland -- seeded by home-manager activation
    background = #1e1e2e
    foreground = #cdd6f4
    EOF
    [ -e "$STATE_DIR/nvim.generated.lua" ] || cat > "$STATE_DIR/nvim.generated.lua" <<'EOF'
    -- managed by syland -- seeded by home-manager activation
    return {
    background = "#1e1e2e", foreground = "#cdd6f4", accent = "#89b4fa",
    red = "#f38ba8", green = "#a6e3a1", yellow = "#f9e2af",
    comment = "#6c7086", cursorline = "#313244", visual = "#45475a",
    pmenu = "#292c3c", pmenu_sel = "#3c4260",
    diff_add = "#2b3b32", diff_delete = "#3d2b30", diff_change = "#3d3a2b",}
    EOF
    [ -e "$STATE_DIR/hyprland.generated.lua" ] || cat > "$STATE_DIR/hyprland.generated.lua" <<'EOF'
    -- managed by syland -- seeded by home-manager activation
    return { ["col.active_border"] = "rgba(89b4faff)", ["col.inactive_border"] = "rgba(313244ff)" }
    EOF
  '';
}
